[package]
name = "cygaz"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }
cygaz-lib = { path = "cygaz-lib" }
actix-web = "4.0.1"
serde_json = "1.0.79"
log = "0.4.16"
envy = "0.4.2"
uuid = { version = "1.0.0-alpha.1", features = ["serde", "v4", "fast-rng"] }
reqwest = { version = "0.11.10", features = ["blocking"] }
tokio = { version = "1.17.0", features = ["full"] }
tokio-cron-scheduler = "0.6.2"

[profile.release]
strip = "debuginfo"
opt-level = 's'  # Optimize for size.
lto = true # Link Time Optimization (LTO)
