[package]
name = "cygaz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
cygaz-lib = { path = "cygaz-lib" }
actix-web = "4"
serde_json = "1.0"
log = "0.4.14"
envy = "0.4.2"
