[package]
name = "cygaz-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.10.1", features = ["macros"] }
reqwest = { version = "0.11.10", features = ["json", "blocking", "cookies", "gzip", "brotli", "deflate", "multipart"] }
url = { version = "2.2.2", features = ["serde"] }
serde_json = "1.0.79"
serde = "1.0.136"
scraper = "0.12.0"

[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }
